apiVersion: v1
kind: Secret
metadata:
  name: english-jatel-secrets
  namespace: english-jatel
type: Opaque
stringData:
  OPENROUTER_API_KEY: "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"
  SESSION_SECRET: "5d94e69f24489a14baecf03f21470b1d76a94a771e685f4c0f48299679b22f0d"
  ADMIN_USER: "admin"
  ADMIN_PASS: "admin123"
