apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: britlearn-site-data
  namespace: britlearn-academy-site
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
