apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: britlearn-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/britlearn-app.git
    targetRevision: main
    path: k8s
    kustomize:
      images:
        - updateinformatica/britlearn-app:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: britlearn-academy-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
