apiVersion: v1
kind: ConfigMap
metadata:
  name: britlearn-app-config
  namespace: britlearn-academy-app
data:
  ADMIN_USER: "admin"
  EDGE_TTS_VOICE: "en-US-GuyNeural"
  DATA_DIR: "/app/data"
  SEED_USERNAME: "britlearn"
  SEED_PASSWORD: "CHANGE_ME"
  IMAGE: "updateinformatica/britlearn-app:latest"
