apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: britlearn-app-data
  namespace: britlearn-academy-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
